### ISSUE TITLE
Maven web app cannot be deployed inside airgap

### ISSUE THREAD

**Issue by ryanmoran** [vmware-tanzu/application-accelerator-samples#147]
The [`tanzu-java-web-app` sample](https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/tanzu-java-web-app) vendors the `mvnw`, `mvnw.cmd`, and `.mvn/wrapper/maven-wrapper.properties` files.

Unfortunately, this makes it quite a bit less intuitive to deploy this application inside of an airgapped installation. Specifically, the `maven-wrapper.properties` file contains URLs that refer to locations on the open internet:

```
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.1/apache-maven-3.8.1-bin.zip
wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.1.1/maven-wrapper-3.1.1.jar
```

Users trying to deploy this app into an airgapped environment will just see an unexplained connection timeout error when their app is being built by the Tanzu Java buildpack. Specifically, the buildpack is trying to call into `mvnw`, which then is referencing these addresses on the public internet.

The Java Buildpack (specifically, the Maven Buildpack) is capable of installing Maven dependencies without needing for this `mvnw` file or its configuration to be checked in.

As a resolution, we've recommended to users attempting to deploy this application into offline environments remove the above listed files. Would we consider doing the same here in the canonical sample repo?

**Comment by trisberg** [comment]
We could consider removing these and rely on Maven/Gradle being provided by buildpacks. We would need to confirm that live update and debug works without these files present for both VSCode and IntelliJ plugins

**Comment by paulcwarren** [comment]
It is pretty standard to include "wrappers" in java projects though @trisberg 

Are there other options here that *may* be better?
- keep the wrappers but make them optional so they can be excluded by users in airgapped envs
- add configuration so accelerator user can enter their internal maven repository (and this is how we set it up for testing airgapped BTW)

**Comment by kdvolder** [comment]
The purpose of the wrapper is to point at a version of maven to use for the project. This is an important function (without it the user has no clue which version of maven this project is supposed to work with and they are responsible for somehow figuring this out themselves and installing it locally). So i.m.o removing the wrapper is not a good solution. Instead, I agree with @paulcwarren it would be better to replace the external/public urls with an equivalent that works inside the specific air-gapped environment. Sadly we cannot put that url in the files since it it probably specific to the air-gapped environment. 

So... basically, I think this suggestion of Paul's is probably the best solution:

> add configuration so accelerator user can enter their internal maven repository

**Comment by trisberg** [comment]
The end user does not have to install Maven, they can rely on the buildpack to provide a compatible version of Maven. We could provide an option to include or exclude the wrapper.

**Comment by gnivedita** [comment]
Let's go with exposing an option for including/excluding - we need to provide some guidance in the description when they should exclude it
